format = """
[░▒▓](#a3aed2)\
$username\
$hostname\
[ 󰣇 ](bg:#a2aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
[](fg:#394260 bg:#212736)\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# ~/.config/starship.toml

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = " "
"pictures" = " "
"games" = " "
"desktop" = " "
# ~/.config/starship.toml

# ~/.config/starship.toml

[username]
show_always = true
style_user = "bold fg:black bg:#a2aed2"
style_root = "bg:#9A348E"
format = '[ $user@]($style)'
disabled = false

[hostname]
ssh_only = false
disabled = false
style = "bg:#a2aed2 fg:black"
format = '[$hostname]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
